# Generated by Django 3.0.14 on 2022-02-02 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20220202_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 14, 32, 1, 314320, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 14, 32, 1, 313322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='mysite_post',
        ),
    ]
