# Generated by Django 3.2 on 2022-02-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20220208_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
    ]
